name = "deploys-app--console"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-05-13"

[vars]
API_ENDPOINT = "https://api.deploys.app"
OAUTH2_CLIENT_ID = "deploys-console-dev"
PUBLIC_API_ENDPOINT = "https://api.deploys.app"

[env.production.vars]
API_ENDPOINT = "https://api.deploys.app"
OAUTH2_CLIENT_ID = "deploys-console"
PUBLIC_API_ENDPOINT = "https://api.deploys.app"
