name: Check
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts
    - run: yarn workspaces focus
    - run: yarn lint
    - run: yarn check
