name: Check
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v3
    - uses: asdf-vm/actions/install@v2
    - run: bun install
    - run: bun run lint
    - run: bun run check
