name: Deploy
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      id: auth
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        token_format: access_token
    - uses: docker/login-action@v1
      with:
        registry: asia-southeast1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/setup-buildx-action@v2
      with:
        version: v0.10.2
    - uses: docker/build-push-action@v4
      with:
        push: true
        tags: asia-southeast1-docker.pkg.dev/deploys-app/public/console:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
    - uses: google-github-actions/auth@v1
      id: auth
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        token_format: access_token
        access_token_scopes: https://www.googleapis.com/auth/userinfo.email
    - uses: deploys-app/deploys-action@v1
      with:
        project: deploys-app
        location: gke.cluster-rcf2
        name: console
        image: asia-southeast1-docker.pkg.dev/deploys-app/public/console:${{ github.sha }}
      env:
        DEPLOYS_TOKEN: ${{ steps.auth.outputs.access_token }}
