name: Deploy
on:
  pull_request:

permissions:
  id-token: write   # required — this is the credential
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: deploys-app/build-deploy-action@v1
      with:
        project: deploys-app
        location: gke.cluster-rcf2
        name: console
        port: 8080
        protocol: h2c
        env: |
          OAUTH2_CLIENT_ID=console-pr
        pullSecret: default
